<?php

/**
 * Banners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banners extends BaseBanners
{
    public static function getBanners() {
        $q = Doctrine_Query::create()
            ->select('b.*')
            ->from('Banners b')
            ->where('active = 1')
            ->orderBy('position DESC');
        if ($result = $q->fetchArray()) {
            return $result;
        }
        return array();
    }
    
    public static function findById($id)
    {
        $q = Doctrine_Query::create()
            ->select('b.*')
            ->from('Banners b')
            ->where('b.id = ?', $id);

        if ($result = $q->fetchOne()) {
            return $result->toArray();
        }
    }
    
    public static function listBanners()
    {
        $q = Doctrine_Query::create()
            ->select('b.*')
            ->from('Banners b')
            ->orderBy('position DESC')
            ->andwhere('b.active != -1');
    
        if ($result = $q->fetchArray()) {
            return $result;
        }
        return array();
    }
    
    public static function TrashById($id)
    {
        $q = Doctrine_Query::create()
            ->update('Banners')
            ->set('active', '-1')
            ->where('id = ?', $id)
            ->execute();
    }

}