<?php

/**
 * Tramite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Faq extends BaseFaq
{
    public static function getFaq()
    {
        $q = Doctrine_Query::create()
        ->select('f.*,n.title')
        ->from('Faq f')
        ->innerJoin('f.News n')
        ->where('f.active != -1')
        ->orderBy('title ASC');
        if ($result = $q->fetchArray()) {
            return $result;
        }
    }
    
    public static function findById($id)
    {
        $q = Doctrine_Query::create()
            ->select('f.*')
            ->from('Faq f')
            ->where('f.id = ?', $id);
        
        if ($result = $q->fetchOne()) {
            return $result->toArray();
        }
    }
    
    public static function findPublicByFather($id)
    {
        $q = Doctrine_Query::create()
            ->select('f.*')
            ->from('Faq f')
            ->where('f.news_id = ?', $id)->andWhere('f.active = 1');
           
        if ($result = $q->fetchOne()) {
            return $result->toArray();
        }
    }
    
    public static function TrashById($id)
    {
        $q = Doctrine_Query::create()
            ->update('faq')
            ->set('active', '-1')
            ->where('id = ?', $id)
            ->execute();
    }
}