<?php

/**
 * Poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Poll extends BasePoll
{
    /**
     * 
     * Devuelve el ultimo poll para una categoria, ordenando por la fecha
     * @param int $id categoria sobre la cual quiero el poll
     */
    public static function getByCategory($id) {
        $q = new Doctrine_Query();
        $result = $q->select()
            ->from('Poll')
            ->where("category = ?", $id)
            ->andWhere('active = 1')
            ->orderBy('creation_date DESC, id DESC')
            ->limit('1')
            ->execute();
        return $result;
    }

    public static function fetchAll()
    {
        $q = Doctrine_Query::create()
        ->select('p.*')
        ->from('Poll p')
        ->orderBy('p.creation_date DESC, p.id DESC')
        ;
    
        if ($result = $q->fetchArray()) {
            return $result;
        }
    }
}