<?php
/**
 * News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Predeterminar extends BasePredeterminar
{
    public static function findPortada()
    {
        $q = Doctrine_Query::create()
            ->select('
                p.*
           ')
            ->from('Predeterminar p')
            ->where('p.element = ?','portada')
            ->limit(1)
            ;
        if ($result = $q->fetchOne()) {
            $return = $result->toArray();
            return $return;
        }
    }
    
    public static function publicarPortada($id)
    {
        return Doctrine_Query::create()
        ->update('Predeterminar')
        ->set('value', $id)
        ->where('element = "portada"')
        ->execute();
    }
}