<?php

/**
 * Tramite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tramite extends BaseTramite
{
    public static function getPublicTramites()
    {
        $q = Doctrine_Query::create()
        ->select('t.*')
        ->from('Tramite t')
        ->orderBy('title ASC')
        ->andwhere('t.active = 1');
        
        if ($result = $q->fetchArray()) {
            return $result;
        }
        return array();
    }
    public static function listarTramites()
    {
        $q = Doctrine_Query::create()
        ->select('t.*')
        ->from('Tramite t')
        ->orderBy('title ASC')
        ->andwhere('t.active != -1');
    
        if ($result = $q->fetchArray()) {
            return $result;
        }
        return array();
    }
    
    public static function findById($id)
    {
        $q = Doctrine_Query::create()
            ->select('
                t.*,
                g.*
            ')
            ->from('Tramite t')
            ->leftJoin('t.Geolocalization g')
            ->where('t.id = ?', $id);
        
        if ($result = $q->fetchOne()) {
            return $result->toArray();
        }
    }
    
    public static function TrashById($id)
    {
        $q = Doctrine_Query::create()
        ->update('Tramite')
        ->set('active', '-1')
        ->where('id = ?', $id)
        ->execute();
    }

}