<?php

/**
 * BasePredeterminar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $element
 * @property integer $value
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePredeterminar extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('predeterminar');
        $this->hasColumn('element', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
        $this->hasColumn('value', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}