SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE  TABLE IF NOT EXISTS `argentinacomparte`.`poll` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `category` INT(10) UNSIGNED NOT NULL ,
  `title` VARCHAR(255) NOT NULL ,
  `option1` VARCHAR(255) NOT NULL ,
  `option2` VARCHAR(255) NOT NULL ,
  `option3` VARCHAR(255) NULL DEFAULT NULL ,
  `option4` VARCHAR(255) NULL DEFAULT NULL ,
  `creation_date` DATETIME NULL DEFAULT NULL ,
  `active` TINYINT(1) NULL DEFAULT NULL ,
  `optionOneVotes` INT(11) NOT NULL DEFAULT 0 ,
  `optionTwoVotes` INT(11) NOT NULL DEFAULT 0 ,
  `optionThreeVotes` INT(11) NULL DEFAULT 0 ,
  `optionFourVotes` INT(11) NULL DEFAULT 0 ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_poll_category1` (`category` ASC) ,
  CONSTRAINT `fk_poll_category1`
    FOREIGN KEY (`category` )
    REFERENCES `argentinacomparte`.`category` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;