<h2>Preguntas Frecuentes</h2>
<table id="formatotabla" class="display">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>id</th>
      <th>Política pública relacionada</th>
      <th>fecha</th>
      <th>estado</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php if (count($this->faq)): ?>
  <?php echo $this->partialLoop('admin/partials/listar-row-faq.phtml', $this->faq) ?>
<?php endif; ?>
  </tbody>
</table>
