<h2>Noticias</h2>
<table id="formatotabla" class="display">
  <thead>
    <tr>
      <th>Acciones</th>
      <th>id</th>
      <th>titulo</th>
      <th>fecha</th>
      <th>estado</th>
      <th>&nbsp;</th>
      <th>política pública</th>
    </tr>
  </thead>
  <tbody>
  <?php
  if (count($this->noticias)) {
      echo $this->partialLoop('admin/partials/listar-row-noticia.phtml', $this->noticias);
  }
  ?>
  </tbody>
</table>
