<tr>
    <td><a class="btn btn-success" title="editar" href="/admin/editar-banner/id/<?php echo $this->id ?>"><i class="icon-pencil icon-white"></i></a>
    <a class="btn" title="ver banner" href="#" data-toggle="modal"
        onclick="return MyDialogs2.loadConfirmationModal('<?php echo $this->id ?>', '<?php echo $this->image ?>')" ><i class="icon-eye-open"></i></a>
        
    </td>
        <td><?php echo $this->id ?>
    </td>
        <td><?php echo $this->title ?>
    </td>
        <td><?php echo $this->position ?>
    </td>
        <td><?php echo ($this->active==1)? 'publicado':'borrador' ?>
    </td>
    <td><a class="btn btn-danger" title="eliminar" href="#" 
            onclick="return MyDialogs.loadConfirmationModal('<?php echo $this->id ?>', '/admin/a-papelera-banner/id/<?php echo $this->id ?>/volver/listar-banners', 
                'El siguiente banner será eliminado', 
                '<?php echo $this->title ?>','');"><i class="icon-trash icon-white"></i></a>
    </td>

</tr>
