<tr>
  <td>
    <a class="btn btn-success" title="editar" href="/admin/noticia-step-one/<?php echo $this->id ?>"><i class="icon-pencil icon-white"></i></a>
    <a class="btn btn-success" title="galeria de imagenes" href="/admin/noticia-step-two/<?php echo $this->id ?>"><i class="icon-camera icon-white"></i></a>
    <a class="btn btn-success" title="geolocalizar" href="/admin/noticia-step-three/<?php echo $this->id ?>"><i class="icon-map-marker icon-white"></i></a>
    <a class="btn btn-success" data-id="<?php echo $this->id ?>" title="predeterminar" href="javascript:;"><i class="icon-white icon-star<?php echo !$this->default ? '-empty': '';?>"></i></a>
    <a class="btn" target="_BLANK" title="ver" href="/ver-mas/id/<?php echo $this->id ?>/<?php echo My_Filter_Slug::filter($this->title);?>"><i class="icon-eye-open"></i></a>
  </td>
  <td>
    <?php echo $this->id ?>
  </td>
  <td>
    <?php echo $this->title ?>
  </td>
  <td>
    <?php echo $this->creation_date ?>
  </td>
  <td>
    <?php echo ($this->active==1)? 'publicado':'borrador' ?>
  </td>
  <td>
    <a class="btn btn-danger" title="eliminar"  href="#" 
       onclick="return MyDialogs.loadConfirmationModal('<?php echo $this->id ?>', '/admin/a-papelera-news/id/<?php echo $this->id ?>/volver/listar-noticias', 
      'La siguiente noticia será eliminada', 
      '<?php echo $this->title ?>','');"
    >
      <i class="icon-trash icon-white"></i>
    </a>
  </td>
  <td>
    <?php echo $this->News['0']['title'] ?>
  </td>
</tr>
